name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: ls -l
    - run: pwd
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag garethbradley/killbill-fargate:$(date +%s)
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.9
      with:
        # The name of the image you would like to push
        name: garethbradley/killbill-fargate:$(date +%s)
        # The login username for the registry
        username: ${{ secrets.DockerHubUsername }}
        # The login password for the registry
        password: ${{ secrets.DockerHubPassword }}
        # Use registry for pushing to a custom registry
#         registry: # optional
#         # Use snapshot to push an additional image
#         snapshot: # optional
#         # Use dockerfile when you would like to explicitly build a Dockerfile
#         dockerfile: # optional
#         # Use workdir when you would like to change the directory for building
#         workdir: # optional
#         # Use buildargs when you want to pass a list of environment variables as build-args
#         buildargs: # optional
#         # Use cache when you have big images, that you would only like to build partially
#         cache: # optional
#         # Use tag_names when you want to push tags/release by their git name
#         tag_names: # optional
